### PR TITLE
Added support for VS 2022

### LINKED ISSUE #14: VS 2022 support
Please would you consider adding support for VS2022? I've gotten so used to having your extension it's hard to live without it, thank you!

Here is a link to documentation:
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

### PR DESCRIPTION
**Pull request by reduckted**
This adds support for Visual Studio 2022. Because this extension consists of just a package class and a command filter, it does not need to be split into multiple projects to support VS 2022 like some more complex extensions do.

⚠️ Due to needing to use the `Microsoft.VisualStudio.SDK` package, versions lower than Visual Studio 2017 (so 2015 and below) can no longer be supported. 

ℹ️ Visual Studio 2017, 2019 and 2022 are supported with these changes.

Changes made:
* Used NuGet package's via `PackageReferences`.
* Changed the package to an `AsyncPackage` (synchronously loading packages is no longer supported).
* Added the icon that was used on the Visual Studio Marketplace
* Added this repository as the "More Info" link that appears in Visual Studio's Extension Manager dialog.
* Reduced the installation targets to "Microsoft.VisualStudio.Community", which will support all higher variants (Community, Pro, Ultimate, etc).

Fixes #14

### CODE REVIEW

**Comment by ow--** [comment]
Oh wow, that's fantastic! Thank you for this! 😍

**Comment by hellfirehd** [comment]
This is great!  How long until it's available on the VS Marketplace?

**Comment by ow--** [comment]
Shouldn't be that long now. Triaged the rest of the stockpile to see if there were any other low hanging fruits. Now I just need to catch up on the github auth changes and remind myself of how to publish.

**Comment by ow--** [comment]
:shipit:

**Pull request merged**
